language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: mgeiger/py3adb
    python: 3.6
  password:
    secure: YMaBGFrkX2GqkMuN/6N0i5kK3cjQBoEUQuzsISz7P2s3oB6oKG+ODmaCiGpUvujzTCkXsvWE5IypADX1yEbQdhtWv3/dd+GspBhv68JFVMO59bKV77W3T1ZCsCtfu8vvOwtIpG4FXJv00rxP9CaPwmOvUMUXuhxrJ4PCbUo2ixXAHcAcrb+MqrciJC5eC9rkPcrFJ9trjrwJ6Izl3PNtV68Rv8K1ysFe+5w/q/tx/2U/UBbOJeZzrMAkUktiUdGC0qwwgnKDFRwSkMjKSMP7PZcqlV95mUOc/NXv2bAPIDtIwssM73dZcubefDedGZy0Y9UDkUfPPBY5UbztXPnSNgMQwS0v5nLUoVLKsR5gxw15hwF4TQrKb+ym+X5KBySz7VZ1HJ5nKD0dABtJLYxAgO8JnNtv8Y28Z41IqcpJQKIYAfkOlt24r82hHrgZicAZobcGJ1V+9+bKSQKBECFbIc0l9qg9c5R0yKGcF9lhOQMllakz+pBcjnMRHZa1BKhccE86z58fqVAVFAi3NhKSmmQakU2i257XhljHuEBG34z2YWaX+ZWiJ8UhT87Cs3kdmhdXvDxl128gUWMKqeHGpLuXwyzFLoDU1qzpwdbk66RClmAxtvT0zDLYh2f+K6LrP0TzQsNVJoDVSd7CPRR2HdNv8KogFqVP3ZlySK9ROOU=
notifications:
  slack:
    secure: HLexZP9kBYyjjDNdVlzu4YzFmCUfEGUSL6lrhWRpHqxiYQoG+LfeXdKMgxLyccZjTvfflo/Hz0uobKfz0pyQkfpCZm58FbutzxqXFtChfyUpgoDnyqus242eoip/QMiapdwQRanEFQmzmYwjMtpePIgQbiwxL/wNQBwAR8kVf32Unm3mDSJbOHlSB1mDimZPckXQwB4KuTzMtflsLaA0pEjfAgAuzRAXw5x3NMFOolws/GuDfkXbHfErVBfqZ+OodKCctVJ7Gm4pl0k/Yg/Fql2vL0rfDbzBRSszM54hrjJqchpoYIh/JV7QCftW04pu6tzBYLt04Wm5+rnrlI8LTK1cIC4lqsaguCimAOL+xSKoI3zJqd0QBpXxBVGgzGfGsAQrpiKHbQYsHvP01ZwJs86ozCpJHnt6uX+Wfm59Eh1TariGsZ/oxu5KSo9NgmicFKq8LIoNjKSbMPje2dI3wtHlGVPhbc9j5IDBgQ91HlmgFwyO4msdwAd7E4ZazlACXa6NGpuJbaQbbbakCgjggyFO1+zbQxWKI3QlpGwN28xaeq0Fv3rqI+epwD9XKm2edoKZSxnc4BMUqRSCpsN1Gs1jeis+W4uLM0fGZZFA5y8wKb34HxIVAGoK2v7QDwukw6//JndTxBdYWqn0631hKEhLue10rLeBGxDh7BOgpYY=
